/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Detail */
        get: operations["scenario_detail_scenarios__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Instance */
        post: operations["create_instance_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve */
        post: operations["solve_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Job */
        post: operations["stop_job_jobs__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescore
         * @description Re-simulate the job's current plan at another departure time (time-of-day slider).
         */
        post: operations["rescore_jobs__job_id__rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Incident */
        post: operations["create_incident_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fastest Path */
        get: operations["fastest_path_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/congestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Congestion */
        get: operations["congestion_congestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{experiment}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result File */
        get: operations["result_file_results__experiment___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Latest TomTom per-road-class speed ratios (cached snapshot; refresh=true re-fetches).
         */
        get: operations["live_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/emissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Emissions
         * @description Estimated emissions of the job's current plan (illustrative speed-based curve).
         */
        get: operations["emissions_jobs__job_id__emissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CongestionEdge */
        CongestionEdge: {
            /** A */
            a: [
                number,
                number
            ];
            /** B */
            b: [
                number,
                number
            ];
            /** Ratio */
            ratio: number;
            /** Road Class */
            road_class: number;
        };
        /** CongestionOut */
        CongestionOut: {
            /** Slot */
            slot: number;
            /** Label */
            label: string;
            /** Edges */
            edges: components["schemas"]["CongestionEdge"][];
        };
        /** CustomerIn */
        CustomerIn: {
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /** Demand */
            demand: number;
        };
        /** EmissionsOut */
        EmissionsOut: {
            /** Kg */
            kg: number;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentCreated */
        IncidentCreated: {
            /** Job Id */
            job_id: string;
            /** Affected Edges */
            affected_edges: number;
        };
        /** IncidentRequest */
        IncidentRequest: {
            /** Job Id */
            job_id: string;
            /** Edges */
            edges?: number[] | null;
            /** Polygon */
            polygon?: [
                number,
                number
            ][] | null;
            /**
             * Factor
             * @default 0.1
             */
            factor: number;
            /** T Start */
            t_start: number;
            /** T End */
            t_end: number;
            /**
             * Budget S
             * @default 10
             */
            budget_s: number;
            /**
             * Mu
             * @default 0
             */
            mu: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** InstanceCreate */
        InstanceCreate: {
            /** Name */
            name?: string | null;
            /** Depot Lon */
            depot_lon: number;
            /** Depot Lat */
            depot_lat: number;
            /** Customers */
            customers: components["schemas"]["CustomerIn"][];
            /** Capacity */
            capacity: number;
            /** N Vehicles */
            n_vehicles?: number | null;
            /**
             * Depart S
             * @default 63000
             */
            depart_s: number;
        };
        /** InstanceDetail */
        InstanceDetail: {
            /** Name */
            name: string;
            /** N Customers */
            n_customers: number;
            /** N Vehicles */
            n_vehicles: number | null;
            /** Capacity */
            capacity: number;
            /** Depart S */
            depart_s: number;
            /**
             * Speed Source
             * @default Calibrated time-of-day profile (synthetic)
             */
            speed_source: string;
            /** Depot */
            depot: [
                number,
                number
            ];
            /** Customers */
            customers: components["schemas"]["CustomerIn"][];
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "solve" | "incident";
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "solving" | "safe_plan" | "optimising" | "done" | "error" | "stopped";
            /** Elapsed S */
            elapsed_s: number;
            /** Message */
            message?: string | null;
            solution?: components["schemas"]["SolutionOut"] | null;
            /** Run Id */
            run_id?: string | null;
        };
        /** LiveOut */
        LiveOut: {
            /** Available */
            available: boolean;
            /** Label */
            label: string;
            /** Fetched At */
            fetched_at?: string | null;
            /** Age S */
            age_s?: number | null;
            /**
             * Ratios
             * @default {}
             */
            ratios: {
                [key: string]: number;
            };
            /** Message */
            message?: string | null;
        };
        /** MetricsOut */
        MetricsOut: {
            /** T */
            T: number;
            /** D */
            D: number;
            /** C */
            C: number;
            /** J */
            J: number;
            /** K */
            K: number;
            /**
             * Route T
             * @default []
             */
            route_T: number[];
            /**
             * Route Load
             * @default []
             */
            route_load: number[];
        };
        /** PathOut */
        PathOut: {
            /** Travel S */
            travel_s: number;
            /** Distance M */
            distance_m: number;
            /** Free Flow Travel S */
            free_flow_travel_s: number;
            /** Geometry */
            geometry: number[][];
            /** Free Flow Geometry */
            free_flow_geometry: number[][];
            /** Depart S */
            depart_s: number;
        };
        /** RescoreOut */
        RescoreOut: {
            /** Depart S */
            depart_s: number;
            metrics: components["schemas"]["MetricsOut"];
        };
        /** ResultTable */
        ResultTable: {
            /** Experiment */
            experiment: string;
            /** Title */
            title: string;
            /** Rows */
            rows: {
                [key: string]: number | string | null;
            }[];
            /** Files */
            files: string[];
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Name */
            name: string;
            /** N Customers */
            n_customers: number;
            /** N Vehicles */
            n_vehicles: number | null;
            /** Capacity */
            capacity: number;
            /** Depart S */
            depart_s: number;
            /**
             * Speed Source
             * @default Calibrated time-of-day profile (synthetic)
             */
            speed_source: string;
        };
        /** SolutionOut */
        SolutionOut: {
            /** Routes */
            routes: number[][];
            /** Depart */
            depart: number;
            metrics: components["schemas"]["MetricsOut"];
            /** Solver */
            solver: string;
            /** Seed */
            seed: number;
            /** Budget */
            budget: number;
            /**
             * Geometry
             * @default []
             */
            geometry: number[][][];
        };
        /** SolveRequest */
        SolveRequest: {
            /** Instance Id */
            instance_id: string;
            /**
             * Solver
             * @default qpso
             * @enum {string}
             */
            solver: "qpso" | "pso" | "ga" | "random" | "pyvrp";
            /**
             * Preset
             * @default fastest
             * @enum {string}
             */
            preset: "fastest" | "balanced" | "low_congestion";
            /**
             * Budget S
             * @default 10
             */
            budget_s: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /** Depart S */
            depart_s?: number | null;
            /**
             * Live
             * @default false
             */
            live: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
    scenario_detail_scenarios__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instance_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_job_jobs__job_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescore_jobs__job_id__rescore_post: {
        parameters: {
            query: {
                depart: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incident_incidents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fastest_path_paths_get: {
        parameters: {
            query: {
                from_lon: number;
                from_lat: number;
                to_lon: number;
                to_lat: number;
                depart: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    congestion_congestion_get: {
        parameters: {
            query: {
                slot: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CongestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultTable"][];
                };
            };
        };
    };
    result_file_results__experiment___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_live_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emissions_jobs__job_id__emissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmissionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
